services:
  db:
    image: postgres:15-alpine
    container_name: good_night_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: good_night_app_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
    container_name: good_night_app_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/good_night_app_development
      RAILS_MAX_THREADS: 5
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  # Optional: Test environment
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: test
    container_name: good_night_app_test
    command: bundle exec rspec
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@db:5432/good_night_app_test
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - test

volumes:
  postgres_data:
  bundle_cache:
